### ISSUE TITLE
BLI deposit - type ... missing data?

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#271] opened 2024-08-02 14:44 UTC
Validation error
Type: Missing data for required field.

I checked all places where this could apply to EOIs but I could not find any type specification missing.

[phzb9-nj208.json](https://github.com/user-attachments/files/16471903/phzb9-nj208.json)

Also for previous BLI issues listed - this is the record that generated all the validation errors.

I have not managed to get to "Deposit" with not validation errors ...

**Comment by edager** [comment] 2024-08-05 11:23
This is a duplicate of #268 and will be fixed in mbdb 0.3.5

**Closed as completed** 2024-08-06 11:17 UTC
